### ISSUE TITLE
请问配置文件是这个格式吗？

### ISSUE THREAD

**Issue by Billyas** [openjmu/jmuEportalAuth#7]
option services '1
option username '20192xxxxxxx
option password 'xxxxxxxxx

**Comment by AlexV525** [comment]
key 是这样，值是不是不太确定，太久没碰了

**Comment by Billyas** [comment]
> key 是这样，值是不是不太确定，太久没碰了

可以了，多谢大佬

**Comment by Billyas** [comment]
值好像 '1  和 '1' 的效果一样
